### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by qgmzhna** [wizardforcel/eloquent-js-3e-zh#6]
位置 : 
一、值，类型和运算符
自动类型转换
错误内容 : 
"字符串和数字转换为布尔值的规则表明，0，NaN和空字符串（""）计为false，而其他所有值都计为true。"

原作中没有这一句 , 而且这句是错的 . NaN == false返回的是false .

**Comment by wizardforcel** [comment]
这句话是存在的

<http://eloquentjavascript.net/01_values.html>

> We can use this functionality as a way to fall back on a default value. If you have a value that might be empty, you can put`||`after it with a replacement value. If the initial value can be converted to false, you’ll get the replacement instead. The rules for converting strings and numbers to Boolean values state that`0`,`NaN`, and the empty string (`""`) count as`false`, while all the other values count as`true`. So`0 || -1`produces`-1`, and`"" || "!?"`yields`"!?"`.

**Comment by wizardforcel** [comment]
再者，`NaN`这个值比较特殊，当`==`两边至少有一个`NaN`时，不会转换，直接判定为`false`。

等价指的是这个：

```js
Boolean(NaN)
// false
new Boolean(NaN)
// Boolean {false}
```

这个在原文中也有说明：

> There is only one value in JavaScript that is not equal to itself, and that is`NaN`(“not a number”).
> 
> ```js
> )console.log(NaN == NaN)
> // → false
> ```
